# Generated by Django 2.0.2 on 2018-07-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frasometre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
