# Generated by Django 2.0.2 on 2018-07-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frasometre', '0002_auto_20180731_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/frasometre/games'),
        ),
    ]
