# Generated by Django 2.0.2 on 2018-07-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frasometre', '0003_auto_20180731_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
