# Generated by Django 2.0.2 on 2018-07-31 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frasometre', '0004_game_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('time', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frasometre.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/frasometre/players')),
                ('games', models.ManyToManyField(blank=True, null=True, to='frasometre.Game')),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='players',
            field=models.ManyToManyField(to='frasometre.Player'),
        ),
    ]
