# Generated by Django 2.0.2 on 2018-07-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frasometre', '0005_auto_20180731_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, to='frasometre.Player'),
        ),
    ]
