# Generated by Django 2.0.2 on 2018-07-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frasometre', '0006_auto_20180731_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='games',
            new_name='players',
        ),
    ]
